{
 "title": "Compute Cloud (Yandex.Cloud)",
 "tags": [
  "yandex.cloud",
  "certificate"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "envName", "label": "envName", "query": { "query": "label_values(envName)" } },
   {
    "name": "resource_id",
    "label": "resource_id",
    "query": {
     "query": "label_values(cpu_utilization{envName=~\"$envName\"},resource_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Virtual Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_utilization{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
     "legendFormat": "{{cpu_name}}; {{resource_id}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "disk_read_bytes{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Read {{device}}"
      },
      {
       "expr": "disk_write_bytes{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Write {{device}}"
      }
     ]
    },
    {
     "title": "Disk operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "disk_read_ops{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Read {{device}}"
      },
      {
       "expr": "disk_write_ops{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Write {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "network_received_bytes{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Recieved {{resource_id}}"
      },
      {
       "expr": "network_sent_bytes{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Sent {{resource_id}}"
      }
     ]
    },
    {
     "title": "Network packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "network_received_packets{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Recieved {{resource_id}}"
      },
      {
       "expr": "network_sent_packets{service=\"compute\", envName=~\"$envName\", resource_id=~\"$resource_id\"}",
       "legendFormat": "Sent {{resource_id}}"
      }
     ]
    }
   ]
  }
 ]
}