{
 "title": "Kafka (Yandex.Cloud)",
 "tags": [
  "kafka",
  "yandex.cloud"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "envName",
    "label": "envName",
    "query": {
     "query": "label_values(kafka_is_alive,envName)"
    }
   },
   {
    "name": "resourceId",
    "label": "resourceId",
    "query": {
     "query": "label_values(kafka_is_alive{envName=\"$envName\"},resource_id)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(kafka_is_alive{envName=~\"$envName\", resource_id=~\"$resourceId\"},host)"
    }
   },
   { "name": "topic", "query": { "query": "label_values(topic)" } },
   {
    "name": "group",
    "query": {
     "query": "label_values(kafka_group_topic_partition_lag{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", topic=~\"$topic\"},group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Main Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alive Brokers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_is_alive{envName=\"$envName\", resource_id=\"$resourceId\"}) by (resource_id)",
     "legendFormat": "{{envName}}: {{host}}"
    }
   ]
  },
  {
   "title": "Topic Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource_id) (kafka_controller_KafkaController_GlobalTopicCount{envName=\"$envName\", resource_id=\"$resourceId\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource_id) (kafka_server_ReplicaManager_PartitionCount{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Ofiline Partitions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_OfflineReplicaCount{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}) by (resource_id)"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(envName, resource_id, host) (rate(kafka_server_BrokerTopicMetrics_BytesIn{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}[$__rate_interval])) / 1024",
       "legendFormat": "Bytes In; {{host}}"
      },
      {
       "expr": "sum by(envName, resource_id, host) (rate(kafka_server_BrokerTopicMetrics_BytesOut{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}[$__rate_interval])) / 1024",
       "legendFormat": "Bytes Out; {{host}}"
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "disk_free_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{envName}}: {{host}}"
      }
     ]
    },
    {
     "title": "Top 5 topics by size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "topk(5, sum(kafka_log_Log_Size{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}) by (topic) / 1073741824)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic partition lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (resource_id, topic, group) (kafka_group_topic_partition_lag{envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", topic=~\"$topic\", group=~\"$group\", group!~\".*(local).*\"})",
       "legendFormat": " topic = {{topic}}; group = {{group}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Requests{resource_type=\"cluster\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}[$__rate_interval])) by (envName, resource_id, request)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Messages In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_BrokerTopicMetrics_MessagesIn{envName=~\"$envName\", resource_type=~\"cluster\", resource_id=\"$resourceId\", host=~\"$host\"}[$__rate_interval])) by (envName, host)",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topics Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topics",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum by (topic) (kafka_log_Log_Size{envName=\"$envName\", resource_id=\"$resourceId\"}) / 1073741824"
      }
     ]
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_idle{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"}",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "cpu_user{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"}",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "cpu_system{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"}",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "cpu_iowait{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"}",
       "legendFormat": "{{systag}}; {{host}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "mem_total_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_active_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_used_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"}/ 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_available_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_cached_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_buffers_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_free_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_shared_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", subcluster_name=\"kafka_subcluster\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      }
     ]
    }
   ]
  }
 ]
}