{
 "title": "PostgreSQL (Yandex.Cloud)",
 "tags": [
  "postgresql",
  "yandex.cloud"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "envName",
    "label": "envName",
    "query": {
     "query": "label_values(postgres_is_alive,envName)"
    }
   },
   {
    "name": "resourceId",
    "label": "resourceId",
    "query": {
     "query": "label_values(postgres_is_alive{envName=\"$envName\"},resource_id)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(postgres_is_alive{envName=~\"$envName\", resource_id=~\"$resourceId\"},host)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(_pg_database_size{envName=~\"$envName\", resource_id=~\"$resourceId\"},dbname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Main Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL Alive",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgres_is_alive{envName=\"$envName\", resource_id=\"$resourceId\"}) by (resource_id)",
     "legendFormat": "{{envName}}: {{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Can Read",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(resource_id) (can_read{envName=\"$envName\", resource_id=\"$resourceId\", service=\"managed-postgresql\"})",
     "legendFormat": "{{envName}}: {{host}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Can Write",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(resource_id) (can_write{envName=\"$envName\", resource_id=\"$resourceId\", service=\"managed-postgresql\"})",
     "legendFormat": "{{envName}}: {{host}}"
    }
   ]
  },
  {
   "title": "Pooler is alive",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(resource_id) (pooler_is_alive{envName=\"$envName\", resource_id=\"$resourceId\", service=\"managed-postgresql\"})",
     "legendFormat": "{{envName}}: {{host}}"
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_idle{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "cpu_user{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "cpu_system{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "cpu_iowait{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "{{systag}}; {{host}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "mem_total_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_active_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_used_bytes{service=\"managed-kafka\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}/ 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_available_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_cached_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_buffers_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_free_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      },
      {
       "expr": "mem_shared_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "{{systag}}; {{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free/Used DIsk Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "disk_free_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "Free; {{host}}"
      },
      {
       "expr": "disk_used_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1073741824",
       "legendFormat": "Used: {{host}}"
      }
     ]
    },
    {
     "title": "Disk read/write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "io_disk1_write_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1048576",
       "legendFormat": "Write Bytes; {{host}}"
      },
      {
       "expr": "io_disk1_read_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"} / 1048576",
       "legendFormat": "Read Bytes: {{host}}"
      }
     ]
    },
    {
     "title": "Disk read/write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "io_disk1_write_count{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Write; {{host}}"
      },
      {
       "expr": "io_disk1_read_count{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Read: {{host}}"
      }
     ]
    },
    {
     "title": "Disk usage by DB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "_pg_database_size{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", dbname=~\"$database\"}",
       "legendFormat": "{{dbname}}"
      }
     ]
    },
    {
     "title": "Total size of WAL files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_wal_size{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "WAL Size; {{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions/statements per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "pooler_xact_count{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Transactions; {{host}}"
      },
      {
       "expr": "pooler_query_count{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Statemenets; {{host}}"
      }
     ]
    },
    {
     "title": "Average transaction/statement time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pooler_avg_xact_time{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Average Transaction Time; {{host}}"
      },
      {
       "expr": "pooler_avg_query_time{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Average Statement Time; {{host}}"
      }
     ]
    },
    {
     "title": "Statement quantiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pooler_query_0_9999{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "99.9%; {{host}}"
      },
      {
       "expr": "pooler_query_0_99{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "99%; {{host}}"
      },
      {
       "expr": "pooler_query_0_9{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "90%; {{host}}"
      },
      {
       "expr": "pooler_query_0_75{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "75%; {{host}}"
      },
      {
       "expr": "pooler_query_0_5{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "50%; {{host}}"
      }
     ]
    },
    {
     "title": "Transaction quantiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pooler_transaction_0_9999{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "99.9%; {{host}}"
      },
      {
       "expr": "pooler_transaction_0_99{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "99%; {{host}}"
      },
      {
       "expr": "pooler_transaction_0_9{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "90%; {{host}}"
      },
      {
       "expr": "pooler_transaction_0_75{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "75%; {{host}}"
      },
      {
       "expr": "pooler_transaction_0_5{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "50%; {{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions read bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (host, resource_id, database) (pg_backend_read_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", database=~\"$database\"})",
       "legendFormat": "{{database}}; {{host}}"
      }
     ]
    },
    {
     "title": "Sessions write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (host, database, resource_id) (pg_backend_write_bytes{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", database=~\"$database\"})",
       "legendFormat": "{{database}}; {{host}}"
      }
     ]
    },
    {
     "title": "Session CPU usage cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum by (host, resource_id, database) (pg_backend_cpu{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", database=~\"$database\"})",
       "legendFormat": "{{database}}; {{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pooler_total_tcp_connections{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\"}",
       "legendFormat": "Used {{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Databases (Table)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Databases",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "_pg_database_size{service=\"managed-postgresql\", envName=~\"$envName\", resource_id=~\"$resourceId\", host=~\"$host\", dbname=~\"$database\"}"
      }
     ]
    }
   ]
  }
 ]
}